---
- name: Uninstall old versions of dockers if present
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: install dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2


- name: add Docker’s official repo
  yum_repository:
    name: docker-ce
    baseurl: 'https://download.docker.com/linux/centos/docker-ce.repo'
